CREATE TABLE products
(id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 name TEXT NOT NULL,
 category TEXT NOT NULL,
 brand TEXT NOT NULL,
 description TEXT NOT NULL,
 color TEXT,
 date_added date NOT NULL,
PRIMARY KEY (id));